import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
   container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
   },
   mainView: {
      zIndex: 1,
      flex: 1,
      position: 'absolute',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      height: '70%',
      top: '30%',
      backgroundColor: 'white',
      borderTopLeftRadius: 50,
   },
   logoBanner: {
      zIndex: -1,
      resizeMode: 'cover',
      height: '100%',
   },
   textInput: {
      backgroundColor: 'none',
      padding: 10,
      width: 250,
      marginHorizontal: 6,
   },
   passwordInputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      textAlign: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 8,
      paddingVertical: 8,
      marginVertical: 8,
      borderWidth: 1,
      borderColor: 'gray',
      borderRadius: 12,
      width: 300,
   },
   textInputPw: {
      backgroundColor: 'none',
      padding: 10,
      width: 250,
      marginHorizontal: 6,
   },
   textLogin: {
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 20,
   },
   loginLogoWrap: {
      justifyContent: 'center',
      alignItems: 'center',
      top: 10,
      position: 'relative',
   },
   logo: {
      width: 100,
      height: 100,
   },
   buttonWrap: {
      width: 300,
      height: 50,
      borderRadius: 10,
      verticalAlign: 'auto',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      color: 'white',
      backgroundColor: 'black',
   },
   button: {
      fontSize: 16,
      color: 'white',
   },
   signup: {
      width: 200,
      height: 50,
      borderRadius: 10,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      color: 'black',
   },
   textRegister: {
      color: 'black',
      fontSize: 16,
      fontWeight: 'bold',
   },
   logingg: {
      width: 100,
      justifyContent: 'center',
      alignItems: 'center',
   },
});
